### ISSUE TITLE
[2.0.0] Maybe catching Serverlist on startup / background?

### ISSUE THREAD

**Issue by guitronimo** [Tragio/TacticalOps-Launcher#2]
Not sure if this is possible in the framework that you use:

When you click the serverlist, it takes nearly 20 Seconds from my connection to have something displayed. 
Maybe its possible to catch the Serverlist right at starup of the launcher in background. 

This is possibly 333Networks JSON api. Then as a general idea:
- Grabbing the JSON Object once
- Create an own JSON or array with Gametype sorted by IP:Port 

Example idea:
`var MyFilteredServerList = ["xxx.xxx.xxx.xxx:port","xx.xx.xxx.xxx:port"]; `

Then in the Serverlist doing requests / polls on individual defined servers:
`"https://master.333networks.com/json/ut/" + "MyFilterdServerlist[i]";`

These objects are there almost immediately. 

Again, just as an idea. Not required loading the full UT List over and over again when you clicked a serverinfo and then clicking the list again. 

Cheers

**Comment by Tragio** [comment]
In the last version, after it's fetched once, it's cached. Thank you for the suggestion 🙏
